#Demonstration of iprpy code design

###Initial Imports

In [1]:
#standard library imports
import sys

#external library imports
import numpy as np

#custom library import
#Need to specify path to the folder containing iprpy
sys.path.append('IPR')
import iprpy

##Atom Class

__Class Atom is used to hold per-atom properties.  The Atom always has an integer type, atype, and 3D position vector, pos.  Interacting with the per-atom properties is controlled by methods.__

In [2]:
atom1 = iprpy.Atom(atype = 1, pos = [1.23, 4.56, 7.89])

__Accessing the values:__

In [3]:
print atom1.atype()
print atom1.pos()
print atom1.pos(0)
print atom1.pos(1)
print atom1.pos(2)

1
[ 1.23  4.56  7.89]
1.23
4.56
7.89


__The same methods can be used to set the per-atom properties:__

In [4]:
atom1.atype(4)
print atom1.atype()
atom1.pos((-9.87, -6.54, -3.21))
print atom1.pos()

4
[-9.87 -6.54 -3.21]


__While these are the only two properties the atom must have, others can be dynamically assigned and accessed using the prop() method.__

In [5]:
#All non-defined property names return None
print atom1.prop('charge')

#Set the propery
atom1.prop('charge', -1.9)

#Now it's value is returned
print atom1.prop('charge')

None
-1.9


__The method prop() can also be used with atype and pos:__

In [6]:
atom1.prop('atype', 2)
print atom1.prop('atype')

atom1.prop('pos', (12.3, 45.6, 78.9))
print atom1.prop('pos')
print atom1.prop('pos', 0)
print atom1.prop('pos', 1)
print atom1.prop('pos', 2)

2
[ 12.3  45.6  78.9]
12.3
45.6
78.9


__The full list of assigned atomic properties can be obtained using prop_list():__

In [7]:
print atom1.prop_list()

['atype', 'pos', 'charge']


##Box class

__The Box class defines a geometric parallelopid which can be used to define any system that can be periodic in all three directions.  In this way, the parameters of the Box can be associated with either an entire atomic system, or a single unit cell.__

In [8]:
box1 = iprpy.Box()

__By default, the box is initialized to be a unit cube with direction vectors [1, 0, 0], [0, 1, 0], [0, 0, 1] and origin at [0, 0, 0].  The parameters of the box can be retrieved in a number of different formats using the get() method.__

In [9]:
print 'Vector representation:'
print 'avect  =', box1.get('avect')
print 'bvect  =', box1.get('bvect')
print 'cvect  =', box1.get('cvect')
print 'origin =', box1.get('origin')
print 
print 'Crystallographic representation:'
print 'a     =', box1.get('a')
print 'b     =', box1.get('b')
print 'c     =', box1.get('c')
print 'alpha =', box1.get('alpha')
print 'beta  =', box1.get('beta')
print 'gamma =', box1.get('gamma')
print
print 'LAMMPS representations:'
print 'xlo xhi  =', box1.get('xlo'), box1.get('xhi')
print 'ylo yhi  =', box1.get('ylo'), box1.get('yhi')
print 'zlo zhi  =', box1.get('zlo'), box1.get('zhi')
print 'lx ly lz =', box1.get('lx'), box1.get('ly'), box1.get('lz')
print 'xy xz yz =', box1.get('xy'), box1.get('xz'), box1.get('yz')

Vector representation:
avect  = [ 1.  0.  0.]
bvect  = [ 0.  1.  0.]
cvect  = [ 0.  0.  1.]
origin = [ 0.  0.  0.]

Crystallographic representation:
a     = 1.0
b     = 1.0
c     = 1.0
alpha = 90.0
beta  = 90.0
gamma = 90.0

LAMMPS representations:
xlo xhi  = 0.0 1.0
ylo yhi  = 0.0 1.0
zlo zhi  = 0.0 1.0
lx ly lz = 1.0 1.0 1.0
xy xz yz = 0.0 0.0 0.0


__The initilizer also allows for Boxes to be constructed by setting any of these above parameters.  However, as the different parameters are not independent of each other, setting the Box parameters is controlled through three different set methods.  The initilizer will call one of the set methods if all supplied parameters are consistent with that method.__  

__Note that the various components of the box cannot be independenly set. Rather, all necessary components must be given at the same time either when the Box is created, or using one of the three set methods.__

###set_vectors()

__The set_vectors() method allows for the Box to be defined using the 3D direction vectors:__

In [10]:
box1.set_vectors(avect = [2.4, 0.0, 0.0], 
                 bvect = [0.0, 3.2, 0.0], 
                 cvect = [0.0, 0.0, 2.7], 
                 origin = [1, 1, 1])

print 'Vector representation:'
print 'avect  =', box1.get('avect')
print 'bvect  =', box1.get('bvect')
print 'cvect  =', box1.get('cvect')
print 'origin =', box1.get('origin')
print 
print 'Crystallographic representation:'
print 'a     =', box1.get('a')
print 'b     =', box1.get('b')
print 'c     =', box1.get('c')
print 'alpha =', box1.get('alpha')
print 'beta  =', box1.get('beta')
print 'gamma =', box1.get('gamma')
print
print 'LAMMPS representations:'
print 'xlo xhi  =', box1.get('xlo'), box1.get('xhi')
print 'ylo yhi  =', box1.get('ylo'), box1.get('yhi')
print 'zlo zhi  =', box1.get('zlo'), box1.get('zhi')
print 'lx ly lz =', box1.get('lx'), box1.get('ly'), box1.get('lz')
print 'xy xz yz =', box1.get('xy'), box1.get('xz'), box1.get('yz')

Vector representation:
avect  = [ 2.4  0.   0. ]
bvect  = [ 0.   3.2  0. ]
cvect  = [ 0.   0.   2.7]
origin = [1, 1, 1]

Crystallographic representation:
a     = 2.4
b     = 3.2
c     = 2.7
alpha = 90.0
beta  = 90.0
gamma = 90.0

LAMMPS representations:
xlo xhi  = 1 3.4
ylo yhi  = 1 4.2
zlo zhi  = 1 3.7
lx ly lz = 2.4 3.2 2.7
xy xz yz = 0.0 0.0 0.0


__For set vectors avect, bvect and cvect must always be supplied, and they must follow the right hand rule. If origin is not given, then it is set to [0, 0, 0].  Also, the vectors are always transformed to be consistent with how LAMMPS defines them, i.e. avect[1] == avect[2] == bvect[2] == 0.__

In [11]:
box1.set_vectors(avect = [2.4, 0.1, -0.1], 
                 bvect = [0.3, 3.2, 1.0], 
                 cvect = [-0.5, 1.1, 2.7])

print 'Vector representation:'
print 'avect  =', box1.get('avect')
print 'bvect  =', box1.get('bvect')
print 'cvect  =', box1.get('cvect')
print 'origin =', box1.get('origin')
print 
print 'Crystallographic representation:'
print 'a     =', box1.get('a')
print 'b     =', box1.get('b')
print 'c     =', box1.get('c')
print 'alpha =', box1.get('alpha')
print 'beta  =', box1.get('beta')
print 'gamma =', box1.get('gamma')
print
print 'LAMMPS representations:'
print 'xlo xhi  =', box1.get('xlo'), box1.get('xhi')
print 'ylo yhi  =', box1.get('ylo'), box1.get('yhi')
print 'zlo zhi  =', box1.get('zlo'), box1.get('zhi')
print 'lx ly lz =', box1.get('lx'), box1.get('ly'), box1.get('lz')
print 'xy xz yz =', box1.get('xy'), box1.get('xz'), box1.get('yz')

Vector representation:
avect  = [ 2.40416306  0.          0.        ]
bvect  = [ 0.39098846  3.34322121  0.        ]
cvect  = [-0.56568542  1.88177093  2.21109434]
origin = [ 0.  0.  0.]

Crystallographic representation:
a     = 2.40416305603
b     = 3.36600653594
c     = 2.95803989155
alpha = 52.4369027887
beta  = 101.024958242
gamma = 83.3295810437

LAMMPS representations:
xlo xhi  = 0.0 2.40416305603
ylo yhi  = 0.0 3.34322120532
zlo zhi  = 0.0 2.21109433854
lx ly lz = 2.40416305603 3.34322120532 2.21109433854
xy xz yz = 0.39098845548 -0.565685424949 1.88177092816


###set_abc()

__The set_abc() method is used to define the system using crystallographic parameters:__  

In [12]:
box1.set_abc(a = 4.5, 
             b = 4.5, 
             c = 4.5, 
             alpha = 90, 
             beta = 90, 
             gamma = 90,
             origin = [-2.25, -2.25, -2.25])

print 'Vector representation:'
print 'avect  =', box1.get('avect')
print 'bvect  =', box1.get('bvect')
print 'cvect  =', box1.get('cvect')
print 'origin =', box1.get('origin')
print 
print 'Crystallographic representation:'
print 'a     =', box1.get('a')
print 'b     =', box1.get('b')
print 'c     =', box1.get('c')
print 'alpha =', box1.get('alpha')
print 'beta  =', box1.get('beta')
print 'gamma =', box1.get('gamma')
print
print 'LAMMPS representations:'
print 'xlo xhi  =', box1.get('xlo'), box1.get('xhi')
print 'ylo yhi  =', box1.get('ylo'), box1.get('yhi')
print 'zlo zhi  =', box1.get('zlo'), box1.get('zhi')
print 'lx ly lz =', box1.get('lx'), box1.get('ly'), box1.get('lz')
print 'xy xz yz =', box1.get('xy'), box1.get('xz'), box1.get('yz')

Vector representation:
avect  = [ 4.5  0.   0. ]
bvect  = [ 0.   4.5  0. ]
cvect  = [ 0.   0.   4.5]
origin = [-2.25, -2.25, -2.25]

Crystallographic representation:
a     = 4.5
b     = 4.5
c     = 4.5
alpha = 90.0
beta  = 90.0
gamma = 90.0

LAMMPS representations:
xlo xhi  = -2.25 2.25
ylo yhi  = -2.25 2.25
zlo zhi  = -2.25 2.25
lx ly lz = 4.5 4.5 4.5
xy xz yz = 0.0 0.0 0.0


__By default, any unsupplied angles (alpha, beta, and gamma) are automatically assumed to be 90, and the origin at [0,0,0].__  

In [13]:
box1.set_abc(a = 3.2, 
             b = 3.2, 
             c = 3.2)

print 'Vector representation:'
print 'avect  =', box1.get('avect')
print 'bvect  =', box1.get('bvect')
print 'cvect  =', box1.get('cvect')
print 'origin =', box1.get('origin')
print 
print 'Crystallographic representation:'
print 'a     =', box1.get('a')
print 'b     =', box1.get('b')
print 'c     =', box1.get('c')
print 'alpha =', box1.get('alpha')
print 'beta  =', box1.get('beta')
print 'gamma =', box1.get('gamma')
print
print 'LAMMPS representations:'
print 'xlo xhi  =', box1.get('xlo'), box1.get('xhi')
print 'ylo yhi  =', box1.get('ylo'), box1.get('yhi')
print 'zlo zhi  =', box1.get('zlo'), box1.get('zhi')
print 'lx ly lz =', box1.get('lx'), box1.get('ly'), box1.get('lz')
print 'xy xz yz =', box1.get('xy'), box1.get('xz'), box1.get('yz')

Vector representation:
avect  = [ 3.2  0.   0. ]
bvect  = [ 0.   3.2  0. ]
cvect  = [ 0.   0.   3.2]
origin = [ 0.  0.  0.]

Crystallographic representation:
a     = 3.2
b     = 3.2
c     = 3.2
alpha = 90.0
beta  = 90.0
gamma = 90.0

LAMMPS representations:
xlo xhi  = 0.0 3.2
ylo yhi  = 0.0 3.2
zlo zhi  = 0.0 3.2
lx ly lz = 3.2 3.2 3.2
xy xz yz = 0.0 0.0 0.0


__The three lattice constants a, b, and c either all must be given, or none given.  If they are not given, then they are all set equal to 1.0__

In [14]:
box1.set_abc(alpha = 75)

print 'Vector representation:'
print 'avect  =', box1.get('avect')
print 'bvect  =', box1.get('bvect')
print 'cvect  =', box1.get('cvect')
print 'origin =', box1.get('origin')
print 
print 'Crystallographic representation:'
print 'a     =', box1.get('a')
print 'b     =', box1.get('b')
print 'c     =', box1.get('c')
print 'alpha =', box1.get('alpha')
print 'beta  =', box1.get('beta')
print 'gamma =', box1.get('gamma')
print
print 'LAMMPS representations:'
print 'xlo xhi  =', box1.get('xlo'), box1.get('xhi')
print 'ylo yhi  =', box1.get('ylo'), box1.get('yhi')
print 'zlo zhi  =', box1.get('zlo'), box1.get('zhi')
print 'lx ly lz =', box1.get('lx'), box1.get('ly'), box1.get('lz')
print 'xy xz yz =', box1.get('xy'), box1.get('xz'), box1.get('yz')

print
print 'This next line is supposed to fail:'
box1.set_abc(a = 5.2)


Vector representation:
avect  = [ 1.  0.  0.]
bvect  = [ 0.  1.  0.]
cvect  = [ 0.          0.25881905  0.96592583]
origin = [ 0.  0.  0.]

Crystallographic representation:
a     = 1.0
b     = 1.0
c     = 1.0
alpha = 75.0
beta  = 90.0
gamma = 90.0

LAMMPS representations:
xlo xhi  = 0.0 1.0
ylo yhi  = 0.0 1.0
zlo zhi  = 0.0 0.965925826289
lx ly lz = 1.0 1.0 0.965925826289
xy xz yz = 0.0 0.0 0.258819045103

This next line is supposed to fail:


AssertionError: Incorrect Box magnitude!

###set_lengths()

__The set_lengths() method allows for the Box parameters to be set using the LAMMPS style parameters for the lengths, tilt factors, and hi/lo values.  This method allows for two different Box representations to be used during the creation:__

- lengths + tilts + origin
- his + los + tilts

__Mixing parameters of these two representations is not allowed (eg. origin cannot be defined if hi-los are used).  For the lengths representation, origin will be taken to be (0,0,0) if not supplied.  And for both, the tilts (xy, xz and yz) are assumed to be zero if not given.__

In [15]:
box1.set_lengths(lx = 5, 
                 ly = 4, 
                 lz = 2.9, 
                 xy=0.5)

print 'Vector representation:'
print 'avect  =', box1.get('avect')
print 'bvect  =', box1.get('bvect')
print 'cvect  =', box1.get('cvect')
print 'origin =', box1.get('origin')
print 
print 'Crystallographic representation:'
print 'a     =', box1.get('a')
print 'b     =', box1.get('b')
print 'c     =', box1.get('c')
print 'alpha =', box1.get('alpha')
print 'beta  =', box1.get('beta')
print 'gamma =', box1.get('gamma')
print
print 'LAMMPS representations:'
print 'xlo xhi  =', box1.get('xlo'), box1.get('xhi')
print 'ylo yhi  =', box1.get('ylo'), box1.get('yhi')
print 'zlo zhi  =', box1.get('zlo'), box1.get('zhi')
print 'lx ly lz =', box1.get('lx'), box1.get('ly'), box1.get('lz')
print 'xy xz yz =', box1.get('xy'), box1.get('xz'), box1.get('yz')

Vector representation:
avect  = [ 5.  0.  0.]
bvect  = [ 0.5  4.   0. ]
cvect  = [ 0.   0.   2.9]
origin = [ 0.  0.  0.]

Crystallographic representation:
a     = 5.0
b     = 4.03112887415
c     = 2.9
alpha = 90.0
beta  = 90.0
gamma = 82.8749836511

LAMMPS representations:
xlo xhi  = 0.0 5.0
ylo yhi  = 0.0 4.0
zlo zhi  = 0.0 2.9
lx ly lz = 5.0 4.0 2.9
xy xz yz = 0.5 0.0 0.0


In [16]:
box1.set_lengths(xlo = -2, 
                 xhi = 4, 
                 ylo = -2, 
                 yhi = 6, 
                 zlo = -2.9, 
                 zhi = 14, 
                 xz = 2.6)

print 'Vector representation:'
print 'avect  =', box1.get('avect')
print 'bvect  =', box1.get('bvect')
print 'cvect  =', box1.get('cvect')
print 'origin =', box1.get('origin')
print 
print 'Crystallographic representation:'
print 'a     =', box1.get('a')
print 'b     =', box1.get('b')
print 'c     =', box1.get('c')
print 'alpha =', box1.get('alpha')
print 'beta  =', box1.get('beta')
print 'gamma =', box1.get('gamma')
print
print 'LAMMPS representations:'
print 'xlo xhi  =', box1.get('xlo'), box1.get('xhi')
print 'ylo yhi  =', box1.get('ylo'), box1.get('yhi')
print 'zlo zhi  =', box1.get('zlo'), box1.get('zhi')
print 'lx ly lz =', box1.get('lx'), box1.get('ly'), box1.get('lz')
print 'xy xz yz =', box1.get('xy'), box1.get('xz'), box1.get('yz')

Vector representation:
avect  = [ 6.  0.  0.]
bvect  = [ 0.  8.  0.]
cvect  = [  2.6   0.   16.9]
origin = [-2.  -2.  -2.9]

Crystallographic representation:
a     = 6.0
b     = 8.0
c     = 17.0988303694
alpha = 90.0
beta  = 81.2538377374
gamma = 90.0

LAMMPS representations:
xlo xhi  = -2.0 4.0
ylo yhi  = -2.0 6.0
zlo zhi  = -2.9 14.0
lx ly lz = 6.0 8.0 16.9
xy xz yz = 0.0 2.6 0.0


##System class

__Systems are simply combinations of a Box, a list of Atoms, and a tuple of three booleans called pbc.  