#Demonstration of iprpy code design

###Initial Imports

In [1]:
#standard library imports
import sys

#external library imports
import numpy as np

#custom library import
#Need to specify path to the folder containing iprpy
sys.path.append('IPR')
import iprpy

##Atom Class

__Class Atom is used to hold per-atom properties.  The Atom always has an integer type, atype, and 3D position vector, pos.  Interacting with the per-atom properties is controlled by methods.__

In [2]:
atom1 = iprpy.Atom(atype = 1, pos = [1.23, 4.56, 7.89])

__Accessing the values:__

In [3]:
#The string of Atom will return a formatted version of the atype and pos
print 'atom1 returns:', atom1

#No arguments returns the values
print 'atom1.atype() returns:', atom1.atype()
print 'atom1.pos() returns:', atom1.pos()

#integer arguments 0,1,2 return the specified component of the position
print 'atom1.pos(0) returns:', atom1.pos(0)
print 'atom1.pos(1) returns:', atom1.pos(1)
print 'atom1.pos(2) returns:', atom1.pos(2)

atom1 returns: 1 1.2300000000000e+00 4.5600000000000e+00 7.8900000000000e+00
atom1.atype() returns: 1
atom1.pos() returns: [ 1.23  4.56  7.89]
atom1.pos(0) returns: 1.23
atom1.pos(1) returns: 4.56
atom1.pos(2) returns: 7.89


__The same methods can be used to set the per-atom properties:__

In [4]:
#Atype can be set with any integer
atom1.atype(4)
print 'atom1.atype() returns:', atom1.atype()

#pos can be set by giving a list/tuple of three numbers.
atom1.pos((-9.87, -6.54, -3.21))
print 'atom1.pos() returns:', atom1.pos()

atom1.atype() returns: 4
atom1.pos() returns: [-9.87 -6.54 -3.21]


__While these are the only two properties the atom must have, others can be dynamically assigned and accessed using the prop() method.__

In [5]:
#All non-defined property names return None
print "atom1.prop('charge') returns:",  atom1.prop('charge')

#Set the propery
atom1.prop('charge', -1.9)

#Now it's value is returned
print "atom1.prop('charge') returns:",  atom1.prop('charge')

atom1.prop('charge') returns: None
atom1.prop('charge') returns: -1.9


__The method prop() can also be used with atype and pos:__

In [6]:
atom1.prop('atype', 2)
print "atom1.prop('atype') returns:", atom1.prop('atype')

atom1.prop('pos', (12.3, 45.6, 78.9))
print "atom1.prop('pos') returns:", atom1.prop('pos')
print "atom1.prop('pos', 0) returns:", atom1.prop('pos', 0)
print "atom1.prop('pos', 1) returns:", atom1.prop('pos', 1)
print "atom1.prop('pos', 2) returns:", atom1.prop('pos', 2)

atom1.prop('atype') returns: 2
atom1.prop('pos') returns: [ 12.3  45.6  78.9]
atom1.prop('pos', 0) returns: 12.3
atom1.prop('pos', 1) returns: 45.6
atom1.prop('pos', 2) returns: 78.9


__The full list of assigned atomic properties can be obtained using prop_list():__

In [7]:
print "atom1.prop_list() returns:", atom1.prop_list()

atom1.prop_list() returns: ['atype', 'pos', 'charge']


__Properties can be scalers, vectors or 2D arrays with corresponding interactivity.  Once a property has been defined, its size, shape and type (int or float) are fixed.__

In [8]:
atom1.prop('slip', [-1.2, 2.2, 1.2])
print atom1.prop('slip')
print atom1.prop('slip', 0)
print atom1.prop('slip', 1)
print atom1.prop('slip', 2)

[-1.2  2.2  1.2]
-1.2
2.2
1.2


In [9]:
atom1.prop('stress', [[11, 12, 13, 14, 15, 16],
                      [21, 22, 23, 24, 25, 26],
                      [31, 32, 33, 34, 35, 36],
                      [41, 42, 43, 44, 45, 46],
                      [51, 52, 53, 54, 55, 56],
                      [61, 62, 63, 64, 65, 66]])
print atom1.prop('stress')

[[11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]
 [41 42 43 44 45 46]
 [51 52 53 54 55 56]
 [61 62 63 64 65 66]]


In [10]:
print atom1.prop('stress', 0)
print
print atom1.prop('stress', 0, 1)
print atom1.prop_list()

[11 12 13 14 15 16]

12
['atype', 'pos', 'charge', 'slip', 'stress']


In [11]:
atom1.prop('stress', [[11, 12, 13, 14, 15, 16],
                      [21, 22, 23, 24, 25, 26],
                      [31, 32, 33, 34, 35, 36],
                      [41, 42, 43, 44, 45, 46],
                      [51, 52, 53, 54, 55, 56],
                      [61, 62, 63, 64, 65, 66]])

##Box class

__The Box class defines a geometric parallelopid which can be used to define any system that can be periodic in all three directions.  In this way, the parameters of the Box can be associated with either an entire atomic system, or a single unit cell.__

In [12]:
box1 = iprpy.Box()

__By default, the box is initialized to be a unit cube with direction vectors [1, 0, 0], [0, 1, 0], [0, 0, 1] and origin at [0, 0, 0].  The parameters of the box can be retrieved in a number of different formats using the get() method.__

In [13]:
print 'Vector representation:'
print 'avect  =', box1.get('avect')
print 'bvect  =', box1.get('bvect')
print 'cvect  =', box1.get('cvect')
print 'origin =', box1.get('origin')
print 
print 'Crystallographic representation:'
print 'a     =', box1.get('a')
print 'b     =', box1.get('b')
print 'c     =', box1.get('c')
print 'alpha =', box1.get('alpha')
print 'beta  =', box1.get('beta')
print 'gamma =', box1.get('gamma')
print
print 'LAMMPS representations:'
print 'xlo xhi  =', box1.get('xlo'), box1.get('xhi')
print 'ylo yhi  =', box1.get('ylo'), box1.get('yhi')
print 'zlo zhi  =', box1.get('zlo'), box1.get('zhi')
print 'lx ly lz =', box1.get('lx'), box1.get('ly'), box1.get('lz')
print 'xy xz yz =', box1.get('xy'), box1.get('xz'), box1.get('yz')

Vector representation:
avect  = [ 1.  0.  0.]
bvect  = [ 0.  1.  0.]
cvect  = [ 0.  0.  1.]
origin = [ 0.  0.  0.]

Crystallographic representation:
a     = 1.0
b     = 1.0
c     = 1.0
alpha = 90.0
beta  = 90.0
gamma = 90.0

LAMMPS representations:
xlo xhi  = 0.0 1.0
ylo yhi  = 0.0 1.0
zlo zhi  = 0.0 1.0
lx ly lz = 1.0 1.0 1.0
xy xz yz = 0.0 0.0 0.0


__The initilizer also allows for Boxes to be constructed by setting any of these above parameters.  However, as the different parameters are not independent of each other, setting the Box parameters is controlled through three different set methods.  The initilizer will call one of the set methods if all supplied parameters are consistent with that method.__  

__Note that the various components of the box cannot be independenly set. Rather, all necessary components must be given at the same time either when the Box is created, or using one of the three set methods.__

###set_vectors()

__The set_vectors() method allows for the Box to be defined using the 3D direction vectors:__

In [14]:
box1.set_vectors(avect = [2.4, 0.0, 0.0], 
                 bvect = [0.0, 3.2, 0.0], 
                 cvect = [0.0, 0.0, 2.7], 
                 origin = [1, 1, 1])

print 'Vector representation:'
print 'avect  =', box1.get('avect')
print 'bvect  =', box1.get('bvect')
print 'cvect  =', box1.get('cvect')
print 'origin =', box1.get('origin')
print 
print 'Crystallographic representation:'
print 'a     =', box1.get('a')
print 'b     =', box1.get('b')
print 'c     =', box1.get('c')
print 'alpha =', box1.get('alpha')
print 'beta  =', box1.get('beta')
print 'gamma =', box1.get('gamma')
print
print 'LAMMPS representations:'
print 'xlo xhi  =', box1.get('xlo'), box1.get('xhi')
print 'ylo yhi  =', box1.get('ylo'), box1.get('yhi')
print 'zlo zhi  =', box1.get('zlo'), box1.get('zhi')
print 'lx ly lz =', box1.get('lx'), box1.get('ly'), box1.get('lz')
print 'xy xz yz =', box1.get('xy'), box1.get('xz'), box1.get('yz')

Vector representation:
avect  = [ 2.4  0.   0. ]
bvect  = [ 0.   3.2  0. ]
cvect  = [ 0.   0.   2.7]
origin = [1, 1, 1]

Crystallographic representation:
a     = 2.4
b     = 3.2
c     = 2.7
alpha = 90.0
beta  = 90.0
gamma = 90.0

LAMMPS representations:
xlo xhi  = 1 3.4
ylo yhi  = 1 4.2
zlo zhi  = 1 3.7
lx ly lz = 2.4 3.2 2.7
xy xz yz = 0.0 0.0 0.0


__For set vectors avect, bvect and cvect must always be supplied, and they must follow the right hand rule. If origin is not given, then it is set to [0, 0, 0].  Also, the vectors are always transformed to be consistent with how LAMMPS defines them, i.e. avect[1] == avect[2] == bvect[2] == 0.__

In [15]:
box1.set_vectors(avect = [2.4, 0.1, -0.1], 
                 bvect = [0.3, 3.2, 1.0], 
                 cvect = [-0.5, 1.1, 2.7])

print 'Vector representation:'
print 'avect  =', box1.get('avect')
print 'bvect  =', box1.get('bvect')
print 'cvect  =', box1.get('cvect')
print 'origin =', box1.get('origin')
print 
print 'Crystallographic representation:'
print 'a     =', box1.get('a')
print 'b     =', box1.get('b')
print 'c     =', box1.get('c')
print 'alpha =', box1.get('alpha')
print 'beta  =', box1.get('beta')
print 'gamma =', box1.get('gamma')
print
print 'LAMMPS representations:'
print 'xlo xhi  =', box1.get('xlo'), box1.get('xhi')
print 'ylo yhi  =', box1.get('ylo'), box1.get('yhi')
print 'zlo zhi  =', box1.get('zlo'), box1.get('zhi')
print 'lx ly lz =', box1.get('lx'), box1.get('ly'), box1.get('lz')
print 'xy xz yz =', box1.get('xy'), box1.get('xz'), box1.get('yz')

Vector representation:
avect  = [ 2.40416306  0.          0.        ]
bvect  = [ 0.39098846  3.34322121  0.        ]
cvect  = [-0.56568542  1.88177093  2.21109434]
origin = [ 0.  0.  0.]

Crystallographic representation:
a     = 2.40416305603
b     = 3.36600653594
c     = 2.95803989155
alpha = 52.4369027887
beta  = 101.024958242
gamma = 83.3295810437

LAMMPS representations:
xlo xhi  = 0.0 2.40416305603
ylo yhi  = 0.0 3.34322120532
zlo zhi  = 0.0 2.21109433854
lx ly lz = 2.40416305603 3.34322120532 2.21109433854
xy xz yz = 0.39098845548 -0.565685424949 1.88177092816


###set_abc()

__The set_abc() method is used to define the system using crystallographic parameters:__  

In [16]:
box1.set_abc(a = 4.5, 
             b = 4.5, 
             c = 4.5, 
             alpha = 90, 
             beta = 90, 
             gamma = 90,
             origin = [-2.25, -2.25, -2.25])

print 'Vector representation:'
print 'avect  =', box1.get('avect')
print 'bvect  =', box1.get('bvect')
print 'cvect  =', box1.get('cvect')
print 'origin =', box1.get('origin')
print 
print 'Crystallographic representation:'
print 'a     =', box1.get('a')
print 'b     =', box1.get('b')
print 'c     =', box1.get('c')
print 'alpha =', box1.get('alpha')
print 'beta  =', box1.get('beta')
print 'gamma =', box1.get('gamma')
print
print 'LAMMPS representations:'
print 'xlo xhi  =', box1.get('xlo'), box1.get('xhi')
print 'ylo yhi  =', box1.get('ylo'), box1.get('yhi')
print 'zlo zhi  =', box1.get('zlo'), box1.get('zhi')
print 'lx ly lz =', box1.get('lx'), box1.get('ly'), box1.get('lz')
print 'xy xz yz =', box1.get('xy'), box1.get('xz'), box1.get('yz')

Vector representation:
avect  = [ 4.5  0.   0. ]
bvect  = [ 0.   4.5  0. ]
cvect  = [ 0.   0.   4.5]
origin = [-2.25, -2.25, -2.25]

Crystallographic representation:
a     = 4.5
b     = 4.5
c     = 4.5
alpha = 90.0
beta  = 90.0
gamma = 90.0

LAMMPS representations:
xlo xhi  = -2.25 2.25
ylo yhi  = -2.25 2.25
zlo zhi  = -2.25 2.25
lx ly lz = 4.5 4.5 4.5
xy xz yz = 0.0 0.0 0.0


__By default, any unsupplied angles (alpha, beta, and gamma) are automatically assumed to be 90, and the origin at [0,0,0].__  

In [17]:
box1.set_abc(a = 3.2, 
             b = 3.2, 
             c = 3.2)

print 'Vector representation:'
print 'avect  =', box1.get('avect')
print 'bvect  =', box1.get('bvect')
print 'cvect  =', box1.get('cvect')
print 'origin =', box1.get('origin')
print 
print 'Crystallographic representation:'
print 'a     =', box1.get('a')
print 'b     =', box1.get('b')
print 'c     =', box1.get('c')
print 'alpha =', box1.get('alpha')
print 'beta  =', box1.get('beta')
print 'gamma =', box1.get('gamma')
print
print 'LAMMPS representations:'
print 'xlo xhi  =', box1.get('xlo'), box1.get('xhi')
print 'ylo yhi  =', box1.get('ylo'), box1.get('yhi')
print 'zlo zhi  =', box1.get('zlo'), box1.get('zhi')
print 'lx ly lz =', box1.get('lx'), box1.get('ly'), box1.get('lz')
print 'xy xz yz =', box1.get('xy'), box1.get('xz'), box1.get('yz')

Vector representation:
avect  = [ 3.2  0.   0. ]
bvect  = [ 0.   3.2  0. ]
cvect  = [ 0.   0.   3.2]
origin = [ 0.  0.  0.]

Crystallographic representation:
a     = 3.2
b     = 3.2
c     = 3.2
alpha = 90.0
beta  = 90.0
gamma = 90.0

LAMMPS representations:
xlo xhi  = 0.0 3.2
ylo yhi  = 0.0 3.2
zlo zhi  = 0.0 3.2
lx ly lz = 3.2 3.2 3.2
xy xz yz = 0.0 0.0 0.0


__The three lattice constants a, b, and c either all must be given, or none given.  If they are not given, then they are all set equal to 1.0__

In [18]:
box1.set_abc(alpha = 75)

print 'Vector representation:'
print 'avect  =', box1.get('avect')
print 'bvect  =', box1.get('bvect')
print 'cvect  =', box1.get('cvect')
print 'origin =', box1.get('origin')
print 
print 'Crystallographic representation:'
print 'a     =', box1.get('a')
print 'b     =', box1.get('b')
print 'c     =', box1.get('c')
print 'alpha =', box1.get('alpha')
print 'beta  =', box1.get('beta')
print 'gamma =', box1.get('gamma')
print
print 'LAMMPS representations:'
print 'xlo xhi  =', box1.get('xlo'), box1.get('xhi')
print 'ylo yhi  =', box1.get('ylo'), box1.get('yhi')
print 'zlo zhi  =', box1.get('zlo'), box1.get('zhi')
print 'lx ly lz =', box1.get('lx'), box1.get('ly'), box1.get('lz')
print 'xy xz yz =', box1.get('xy'), box1.get('xz'), box1.get('yz')

print
print 'This next line is supposed to fail:'
#box1.set_abc(a = 5.2)


Vector representation:
avect  = [ 1.  0.  0.]
bvect  = [ 0.  1.  0.]
cvect  = [ 0.          0.25881905  0.96592583]
origin = [ 0.  0.  0.]

Crystallographic representation:
a     = 1.0
b     = 1.0
c     = 1.0
alpha = 75.0
beta  = 90.0
gamma = 90.0

LAMMPS representations:
xlo xhi  = 0.0 1.0
ylo yhi  = 0.0 1.0
zlo zhi  = 0.0 0.965925826289
lx ly lz = 1.0 1.0 0.965925826289
xy xz yz = 0.0 0.0 0.258819045103

This next line is supposed to fail:


###set_lengths()

__The set_lengths() method allows for the Box parameters to be set using the LAMMPS style parameters for the lengths, tilt factors, and hi/lo values.  This method allows for two different Box representations to be used during the creation:__

- lengths + tilts + origin
- his + los + tilts

__Mixing parameters of these two representations is not allowed (eg. origin cannot be defined if hi-los are used).  For the lengths representation, origin will be taken to be (0,0,0) if not supplied.  And for both, the tilts (xy, xz and yz) are assumed to be zero if not given.__

In [19]:
box1.set_lengths(lx = 5, 
                 ly = 4, 
                 lz = 2.9, 
                 xy=0.5)

print 'Vector representation:'
print 'avect  =', box1.get('avect')
print 'bvect  =', box1.get('bvect')
print 'cvect  =', box1.get('cvect')
print 'origin =', box1.get('origin')
print 
print 'Crystallographic representation:'
print 'a     =', box1.get('a')
print 'b     =', box1.get('b')
print 'c     =', box1.get('c')
print 'alpha =', box1.get('alpha')
print 'beta  =', box1.get('beta')
print 'gamma =', box1.get('gamma')
print
print 'LAMMPS representations:'
print 'xlo xhi  =', box1.get('xlo'), box1.get('xhi')
print 'ylo yhi  =', box1.get('ylo'), box1.get('yhi')
print 'zlo zhi  =', box1.get('zlo'), box1.get('zhi')
print 'lx ly lz =', box1.get('lx'), box1.get('ly'), box1.get('lz')
print 'xy xz yz =', box1.get('xy'), box1.get('xz'), box1.get('yz')

Vector representation:
avect  = [ 5.  0.  0.]
bvect  = [ 0.5  4.   0. ]
cvect  = [ 0.   0.   2.9]
origin = [ 0.  0.  0.]

Crystallographic representation:
a     = 5.0
b     = 4.03112887415
c     = 2.9
alpha = 90.0
beta  = 90.0
gamma = 82.8749836511

LAMMPS representations:
xlo xhi  = 0.0 5.0
ylo yhi  = 0.0 4.0
zlo zhi  = 0.0 2.9
lx ly lz = 5.0 4.0 2.9
xy xz yz = 0.5 0.0 0.0


In [20]:
box1.set_lengths(xlo = -2, 
                 xhi = 4, 
                 ylo = -2, 
                 yhi = 6, 
                 zlo = -2.9, 
                 zhi = 14, 
                 xz = 2.6)

print 'Vector representation:'
print 'avect  =', box1.get('avect')
print 'bvect  =', box1.get('bvect')
print 'cvect  =', box1.get('cvect')
print 'origin =', box1.get('origin')
print 
print 'Crystallographic representation:'
print 'a     =', box1.get('a')
print 'b     =', box1.get('b')
print 'c     =', box1.get('c')
print 'alpha =', box1.get('alpha')
print 'beta  =', box1.get('beta')
print 'gamma =', box1.get('gamma')
print
print 'LAMMPS representations:'
print 'xlo xhi  =', box1.get('xlo'), box1.get('xhi')
print 'ylo yhi  =', box1.get('ylo'), box1.get('yhi')
print 'zlo zhi  =', box1.get('zlo'), box1.get('zhi')
print 'lx ly lz =', box1.get('lx'), box1.get('ly'), box1.get('lz')
print 'xy xz yz =', box1.get('xy'), box1.get('xz'), box1.get('yz')

Vector representation:
avect  = [ 6.  0.  0.]
bvect  = [ 0.  8.  0.]
cvect  = [  2.6   0.   16.9]
origin = [-2.  -2.  -2.9]

Crystallographic representation:
a     = 6.0
b     = 8.0
c     = 17.0988303694
alpha = 90.0
beta  = 81.2538377374
gamma = 90.0

LAMMPS representations:
xlo xhi  = -2.0 4.0
ylo yhi  = -2.0 6.0
zlo zhi  = -2.9 14.0
lx ly lz = 6.0 8.0 16.9
xy xz yz = 0.0 2.6 0.0


##System class

__The System class is a combination of a Box, box, a list of Atoms, atoms, and a tuple of three booleans, pbc.  The system is initilized by giving values for these three components.  If box is not supplied, then the default Box is used.  If atoms is not supplied, then a blank list is used.  And if pbc is not supplied, the value is set to (True, True, True) indicating that all three directions are periodic.__

In [21]:
sys0 = iprpy.System()

sys1 = iprpy.System(box = iprpy.Box(a=3.54, b=3.54, c=3.54),
                    atoms = [iprpy.Atom(1, (0.00, 0.00, 0.00)),
                             iprpy.Atom(1, (1.77, 1.77, 0.00)),
                             iprpy.Atom(1, (0.00, 1.77, 1.77)),
                             iprpy.Atom(1, (1.77, 0.00, 1.77))],
                    pbc = (True, True, True))               

__Similar to the Atom class, appropriately named methods are used to get and set different parameters.__

__pbc values can be retrieved and set with pbc():__

In [22]:
print 'sys0.pbc() returns:', sys0.pbc()
print 'sys0.pbc(0) returns:', sys0.pbc(0)
print

sys0.pbc(0, False)
print 'sys0.pbc(0) returns:', sys0.pbc(0)

sys0.pbc() returns: (True, True, True)
sys0.pbc(0) returns: True

sys0.pbc(0) returns: False


__The Box and the individual parameters can be accessed using box().  This method, however, does not allow for the box parameters to be set or changed as a separate deform() method is needed to properly handle changes in atom positions due to the box changing (deform() not added yet).__

In [23]:
print "sys0.box() returns:", sys0.box()
print
print "sys0.box('avect') returns:", sys0.box('avect')
print "sys0.box('bvect') returns:", sys0.box('bvect')
print "sys0.box('cvect') returns:", sys0.box('cvect')
print "sys0.box('origin') returns:", sys0.box('origin')
print
print "sys0.box('a') returns:", sys0.box('a')
print "sys0.box('b') returns:", sys0.box('b')
print "sys0.box('c') returns:", sys0.box('c')
print "sys0.box('alpha') returns:", sys0.box('alpha')
print "sys0.box('beta') returns:", sys0.box('beta')
print "sys0.box('gamma') returns:", sys0.box('gamma')
print
print "sys0.box('xlo') returns:", sys0.box('xlo')
print "sys0.box('xhi') returns:", sys0.box('yhi')
print "sys0.box('ylo') returns:", sys0.box('ylo')
print "sys0.box('yhi') returns:", sys0.box('yhi')
print "sys0.box('zlo') returns:", sys0.box('zlo')
print "sys0.box('zhi') returns:", sys0.box('zhi')
print "sys0.box('lx') returns:", sys0.box('lx')
print "sys0.box('ly') returns:", sys0.box('ly')
print "sys0.box('lz') returns:", sys0.box('lz')
print "sys0.box('xy') returns:", sys0.box('xy')
print "sys0.box('xz') returns:", sys0.box('xz')
print "sys0.box('yz') returns:", sys0.box('yz')

sys0.box() returns: <iprpy.Box.Box instance at 0x000000000464FDC8>

sys0.box('avect') returns: [ 1.  0.  0.]
sys0.box('bvect') returns: [ 0.  1.  0.]
sys0.box('cvect') returns: [ 0.  0.  1.]
sys0.box('origin') returns: [ 0.  0.  0.]

sys0.box('a') returns: 1.0
sys0.box('b') returns: 1.0
sys0.box('c') returns: 1.0
sys0.box('alpha') returns: 90.0
sys0.box('beta') returns: 90.0
sys0.box('gamma') returns: 90.0

sys0.box('xlo') returns: 0.0
sys0.box('xhi') returns: 1.0
sys0.box('ylo') returns: 0.0
sys0.box('yhi') returns: 1.0
sys0.box('zlo') returns: 0.0
sys0.box('zhi') returns: 1.0
sys0.box('lx') returns: 1.0
sys0.box('ly') returns: 1.0
sys0.box('lz') returns: 1.0
sys0.box('xy') returns: 0.0
sys0.box('xz') returns: 0.0
sys0.box('yz') returns: 0.0


__The list of Atoms and individual atomic properties can be accessed using the atoms() method.  The order of optional arguments can be thought of as: index, property, value.__

In [24]:
print "sys1.atoms() returns", sys1.atoms()
print 
print "sys1.natoms() returns the number of atoms:", sys1.natoms()
print "sys1.natypes() returns the largest atype:", sys1.natypes()
print
print "sys1.atoms(1) returns", sys1.atoms(1)
print "sys1.atoms(1, 'atype') returns", sys1.atoms(1, 'atype')
print "sys1.atoms(1, 'pos') returns", sys1.atoms(1, 'pos')
print "sys1.atoms(1, 'pos', 0) returns", sys1.atoms(1, 'pos', 0)
print "sys1.atoms(1, 'pos', 1) returns", sys1.atoms(1, 'pos', 1)
print "sys1.atoms(1, 'pos', 2) returns", sys1.atoms(1, 'pos', 2)
print 

print "set value using sys1.atoms(1, 'atype', 2)"
sys1.atoms(1, 'atype', 2)
print "sys1.atoms(1, 'atype') returns", sys1.atoms(1, 'atype')
print "set value using sys1.atoms(1, 'pos', (1.65, 1.89, 0.10))"
sys1.atoms(1, 'pos', (1.65, 1.89, 0.10))
print "sys1.atoms(1, 'pos') returns", sys1.atoms(1, 'pos')
print 

print "sys1.atoms(1, 'my_prop') returns", sys1.atoms(1, 'my_prop')
print "set value using sys1.atoms(1, 'my_prop', 42)"
sys1.atoms(1, 'my_prop', 42)
print "sys1.atoms(1, 'my_prop') returns", sys1.atoms(1, 'my_prop')

sys1.atoms() returns [<iprpy.Atom.Atom instance at 0x0000000004721E88>, <iprpy.Atom.Atom instance at 0x0000000004721AC8>, <iprpy.Atom.Atom instance at 0x0000000004721A08>, <iprpy.Atom.Atom instance at 0x00000000047219C8>]

sys1.natoms() returns the number of atoms: 4
sys1.natypes() returns the largest atype: 1

sys1.atoms(1) returns 1 1.7700000000000e+00 1.7700000000000e+00 0.0000000000000e+00
sys1.atoms(1, 'atype') returns 1
sys1.atoms(1, 'pos') returns [ 1.77  1.77  0.  ]
sys1.atoms(1, 'pos', 0) returns 1.77
sys1.atoms(1, 'pos', 1) returns 1.77
sys1.atoms(1, 'pos', 2) returns 0.0

set value using sys1.atoms(1, 'atype', 2)
sys1.atoms(1, 'atype') returns 2
set value using sys1.atoms(1, 'pos', (1.65, 1.89, 0.10))
sys1.atoms(1, 'pos') returns [ 1.65  1.89  0.1 ]

sys1.atoms(1, 'my_prop') returns None
set value using sys1.atoms(1, 'my_prop', 42)
sys1.atoms(1, 'my_prop') returns 42


__Also, now that the atoms and the Box are tied together, the atomic positions can be given and assigned in scaled fractional coordinates as well.  These are accessed by including scale=True in the arguments for any basic system method that sets or returns atomic values.  Note that accessing the different components of position doesn't work with scale=True.  Not sure that this should be allowed...__

In [25]:
sys2 = iprpy.System(box = iprpy.Box(a=5, b=5, c=5),
                    atoms = [iprpy.Atom(1, (0.0, 0.0, 0.0)),
                             iprpy.Atom(1, (0.5, 0.5, 0.5))],
                    scale = True)

print "Atom 1 at Cartesian position:", sys2.atoms(1, 'pos')
print "Atom 1 at fractional position:", sys2.atoms(1, 'pos', scale=True)
print 
print "Atom 1 being set at fractional position using sys2.atoms(1, 'pos', (0.25, 0.5, 0.5), scale=True)"
sys2.atoms(1, 'pos', (0.25, 0.5, 0.5), scale=True)
print "Atom 1 at Cartesian position:", sys2.atoms(1, 'pos')
print "Atom 1 at fractional position:", sys2.atoms(1, 'pos', scale=True)

Atom 1 at Cartesian position: [ 2.5  2.5  2.5]
Atom 1 at fractional position: [ 0.5  0.5  0.5]

Atom 1 being set at fractional position using sys2.atoms(1, 'pos', (0.25, 0.5, 0.5), scale=True)
Atom 1 at Cartesian position: [ 1.25  2.5   2.5 ]
Atom 1 at fractional position: [ 0.25  0.5   0.5 ]


__Other methods can also be handled at the System level that are dependent on the atoms, box and pbc.  These methods are:__


- scale() converts an atom or 3D vector position from absolute to fractional coordinates.

- unscale() converts an atom or 3D vector position from fractional to absolute coordinates.

- dvect() gives the shortest distance between two points/atoms in the system by considering the periodic boundaries.

- wrap() compares the atomic positions to the box and translates any atoms ouside the periodic box dimensions to an eqivalent position inside the box.

- neighbors() constructs a neighbor list for each atom associated with a supplied cutoff value.

- pt_defect() creates a duplicate system with a point defect added to it.

__The first four of these methods are simple and don't really need much explaining, while the last two are complicated enough that their explanations are better suited elsewhere.__


In [26]:

    for i in xrange(len(sterms)):
        try:
            start = sterms[i].index('[')
            end = sterms[i].index(']')
            pname = sterms[i][:start-1]
            i_index = int(sterms[i][start:end])
            try:
                ssterms = sterms[i][end+1]
                start = ssterms.index('[')
                end = ssterms.index(']')
                j_index = int(ssterms[start:end])
                sterms[i] = (pname, i_index, j_index)
            except:
                sterms[i] = (pname, i_index)
        except:
            pass

In [63]:
sterms = ['id', 'type', 'x', 'y', 'z', 'slip[1]', 'slip[2]', 'slip[3]', 
          'nye[1][1]', 'nye[1][2]', 'nye[1][3]', 'nye[2][1]', 'nye[2][2]', 'nye[2][3]', 'nye[3][1]', 'nye[3][2]', 'nye[3][3]']
print sterms
for i in xrange(len(sterms)):        
    try:
        start = sterms[i].index('[')
        end = sterms[i].index(']')
        pname = sterms[i][:start]
        i_index = int(sterms[i][start+1:end])
        try:
            start2 = sterms[i][end+1:].index('[')
            end2 = sterms[i][end+1:].index(']')
            j_index = int(sterms[i][end+1:][start2+1:end2])
            sterms[i] = (pname, i_index-1, j_index-1)
        except:
            sterms[i] = (pname, i_index-1)
    except:
        sterms[i] = (sterms[i],)
    
    #Change special names
    if sterms[i][0] == 'type':
        assert len(sterms[i]) == 1
        sterms[i] = ('atype',)
        print sterms[i]
    elif sterms[i][0] == 'x':
        assert len(sterms[i]) == 1
        sterms[i] = ('pos', 0)
    elif sterms[i][0] == 'y':
        assert len(sterms[i]) == 1
        sterms[i] = ('pos', 1)
    elif sterms[i][0] == 'z':
        assert len(sterms[i]) == 1
        sterms[i] = ('pos', 2)
    elif sterms[i][0] == 'xs':
        assert len(sterms[i]) == 1
        sterms[i] = ('spos', 0)
    elif sterms[i][0] == 'ys':
        assert len(sterms[i]) == 1
        sterms[i] = ('spos', 1)
    elif sterms[i][0] == 'zs':
        assert len(sterms[i]) == 1
        sterms[i] = ('spos', 2)
    elif sterms[i][0] == 'xu':
        assert len(sterms[i]) == 1
        sterms[i] = ('pos_u', 0)
    elif sterms[i][0] == 'yu':
        assert len(sterms[i]) == 1
        sterms[i] = ('pos_u', 1)
    elif sterms[i][0] == 'zu':
        assert len(sterms[i]) == 1
        sterms[i] = ('pos_u', 2)
    elif sterms[i][0] == 'xsu':
        assert len(sterms[i]) == 1
        sterms[i] = ('spos_u', 0)
    elif sterms[i][0] == 'ysu':
        assert len(sterms[i]) == 1
        sterms[i] = ('spos_u', 1)
    elif sterms[i][0] == 'zsu':
        assert len(sterms[i]) == 1
        sterms[i] = ('spos_u', 2)
    
#build prop_list and prop_shape    
prop_list = []
prop_shape = []
for i in xrange(len(sterms)):
    if sterms[i][0] not in prop_list:
        prop_list.append(sterms[i][0])
        if len(sterms[i]) == 1:
            prop_shape.append(())
        elif len(sterms[i]) == 2:
            maxi = 0
            for j in xrange(i, len(sterms)):
                if sterms[i][0] == sterms[j][0]:
                    if sterms[j][1] > maxi:
                        maxi = sterms[j][1]
            maxi = long(maxi+1)
            prop_shape.append((maxi,))
        elif len(sterms[i]) == 3:
            maxi = 0
            maxj = 0
            for j in xrange(i, len(sterms)):
                if sterms[i][0] == sterms[j][0]:
                    if sterms[j][1] > maxi:
                        maxi = sterms[j][1]
                    if sterms[j][2] > maxj:
                        maxj = sterms[j][2]
            maxi = long(maxi+1)
            maxj = long(maxj+1)
            prop_shape.append((maxi, maxj))
print sterms
print prop_list
print prop_shape
    
        

['id', 'type', 'x', 'y', 'z', 'slip[1]', 'slip[2]', 'slip[3]', 'nye[1][1]', 'nye[1][2]', 'nye[1][3]', 'nye[2][1]', 'nye[2][2]', 'nye[2][3]', 'nye[3][1]', 'nye[3][2]', 'nye[3][3]']
('atype',)
[('id',), ('atype',), ('pos', 0), ('pos', 1), ('pos', 2), ('slip', 0), ('slip', 1), ('slip', 2), ('nye', 0, 0), ('nye', 0, 1), ('nye', 0, 2), ('nye', 1, 0), ('nye', 1, 1), ('nye', 1, 2), ('nye', 2, 0), ('nye', 2, 1), ('nye', 2, 2)]
['id', 'atype', 'pos', 'slip', 'nye']
[(), (), (3L,), (3L,), (3L, 3L)]


In [64]:
prop_dict = {}
prop_dict['a'] = 4
prop_dict['1241'] = 'poo'

for prop_name, prop_value in prop_dict.iteritems():
    print prop_name, prop_value

a 4
1241 poo
